apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pin-vhost
  labels:
    k8s-app: pin-vhost
spec:
  selector:
    matchLabels:
      name: pin-vhost
  template:
    metadata:
      labels:
        name: pin-vhost
    spec:
      tolerations:
      - operator: Exists
      hostPID: true
      containers:
      - name: pin-vhost
        securityContext:
          privileged: true
          # capabilities:
          #  add: #["NET_ADMIN"]
          #    - ALL
        image: quay.io/akaris/pin-vhost:latest
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        command:
        - pin-vhost
        - "-log-level"
        - "2"
        - "-pin-mode"
        - "first" 
        # - "-discovery-mode"
        volumeMounts:
        - name: hostproc
          mountPath: /host/proc
        # If we were pinning the map, we'd want to mount /host/sys, otherwise not:
        # - name: hostsys
        #   mountPath: /host/sys
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
      # - name: hostsys
      #  hostPath:
      #    path: /sys